name: Build and Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Setup Haskell
      uses: haskell/actions/setup@v2
      with:
        ghc-version: '9.4.8'
        cabal-version: '3.8'
    
    - name: Cache Cabal dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cabal/store
          dist-newstyle
        key: ${{ runner.os }}-cabal-${{ hashFiles('**/*.cabal', 'cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-cabal-
    
    - name: Install dependencies
      run: |
        cabal update
        cabal build --only-dependencies
    
    - name: Build Hakyll site executable
      run: cabal build
    
    - name: Build site
      run: |
        # Try to find the executable
        SITE_EXEC=$(find dist-newstyle -name site -type f -executable | head -n 1)
        
        if [ -n "$SITE_EXEC" ]; then
          echo "Found site executable at: $SITE_EXEC"
          $SITE_EXEC rebuild || $SITE_EXEC build
        else
          echo "Using cabal exec"
          cabal exec site rebuild || cabal exec site build
        fi
        
        # Ensure _site directory exists
        mkdir -p _site
        
        # Create a .nojekyll file to disable Jekyll processing
        touch _site/.nojekyll
        
        # Create CNAME file for custom domain
        echo "hyperpolarizability.com" > _site/CNAME
    
    - name: Debug site output
      run: |
        echo "Contents of _site directory:"
        ls -la _site
    
    - name: Setup Pages
      id: pages
      uses: actions/configure-pages@v3
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: '_site'
  
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2